#!/bin/bash

# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Display information about the transfer
echo "Transferring file from $FILE_PATH to $USERNAME@$SERVER_IP:~/"

# Use scp to transfer the file with strict host key checking disabled
scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP":~/

# Check the exit status of the scp command
if [ $? -eq 0 ]; then
  echo "File transfer successful!"
else
  echo "Error: File transfer failed."
fi

